### ISSUE TITLE
Built Unity application fails to load dll

### ISSUE THREAD

**Issue by FrankHermes** [jamesy012/Direct-Input#1]
Hi, we're trying to update an older Unity 5.5 application with new joystick inputs, and for this we use Direct-Input. All works fine in Unity, and also in a built application on my dev machine, but when I install the application on our target PC (a museum exhibit) the application fails to load ControllerInputDll.dll, with error `'The specified module could not be found.'`

All our machines run Windows 10, 64 bits. It doesn't make a difference whether I build a 64 bits executable or a 32 bits one.

What module could be the one that's missing? How can we fix this?

best, Frank

**Comment by jamesy012** [comment]
Hi Frank,
 
That dll is located here [https://github.com/jamesy012/Direct-Input/tree/master/Unity/Assets/JInput/Plugins/DirectInput/64](https://github.com/jamesy012/Direct-Input/tree/master/Unity/Assets/JInput/Plugins/DirectInput/64) 

When you say 'install the application on our target PC' does that mean you have made a build from Unity and copied that over to the other PC?

can you make sure in the build you have that in the yourproject_data folder there is a Plugins folder with that dll in it?

**Comment by FrankHermes** [comment]
Hi James, I've verified that the dll is present, in the Plugins folder of my executable, on every machine I've installed it on. The log message I mentioned earlier (with the error) also states the right path for the dll, but still can't load it. Here it is in full:

> 2020/02/19 12:28:00 - Error    : Failed to load 'C:/Program Files (x86)/T8_Fabriek/T8_Fabriek_Data/Plugins/ControllerInputDll.dll' with error 'The specified module could not be found'. 

The weird thing is, the exe **does** work on my dev PC (that has a lot of Unity editor versions installed), but not on any other PC. So _something else_ must be missing on those other PC's.

**Comment by jamesy012** [comment]
Is there some virus protection software on the computer that would prevent the dll from running correctly?

I'm not quite sure at this stage why it's failing to be honest I haven't seen anything like this before

**Comment by FrankHermes** [comment]
OK thanks anyway. We'll try some other things.

**Comment by FrankHermes** [comment]
Hi James, I got it working by building a new release dll in Visual Studio with the Windows 10 SDK selected. Copied it over the one in the built executable, and now it works.

Thanks for your help and many more thanks for making the full source of your project available!
